# Use root/example as user/password credentials
version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:management
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
